content/urls.py
from django.urls import path

from . import views

app_name = 'content'

urlpatterns = [
    path('', views.game_catalog, name='game_catalog'),
    # path('game_intake/', views.game_intake, name='game_intake'),
    path('<int:game_key>/', views.game_page, name='game_page'),
    # path('<int:game_key>/delete/', views.remove_game, name='remove_game'),
    # path('<int:game_key>/edit/', views.edit_game, name='edit_game'),
]

messaging/urls.py
from django.urls import path

from . import views

app_name = 'messaging'

urlpatterns = [
    path('', views.message_home, name='message_home'),
    path('<int:message_key>/', views.message, name='message'),
    path('create/<int:game_key>/', views.new_message_group, name='create'),
]

steamapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
    path('games/', include('content.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('messaging/', include('messaging.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.get_wishlist, name='get_wishlist'),
    path('<int:game_key>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('<int:game_key>/delete/', views.remove_from_wishlist, name='remove_from_wishlist')
]

content/models.py
from django.db import models
from django.contrib.auth.models import User


class Genre(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Genres"

    def __str__(self):
        return self.name


class Developer(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Developers"

    def __str__(self):
        return self.name


class Games(models.Model):
    genre = models.ForeignKey(Genre, related_name="items", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="item_images", blank=True, null=True)
    price = models.FloatField(default=0)
    on_sale = models.BooleanField(default=False)
    discount = models.FloatField(default=0)
    developers = models.ManyToManyField(Developer, related_name="developers")
    release_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "Games"

    def __str__(self):
        return self.name

content/forms.py
from django import forms
from .models import Games
from .models import Developer

class GameIntakeForm(forms.ModelForm):
    class Meta:
        model = Games
        fields = ('genre', 'name', 'description', 'image', 'price', 'on_sale', 'developers', 'release_date')
        widgets = {
            'genre': forms.Select(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'name': forms.TextInput(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'description': forms.Textarea(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'image': forms.FileInput(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'on_sale': forms.CheckboxInput(),
            'developers': forms.Select(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'release_date': forms.widgets.DateInput(attrs={'type': 'date', 
                'class': 'mx-3 gap-4 w-1/6 h-1/2 py-4 px-6 rounded-xl'
            })
        }
        
class GameEditForm(forms.ModelForm):
    class Meta:
        model = Games
        fields = ('genre', 'name', 'description', 'image', 'price', 'on_sale', 'developers', 'release_date')
        widgets = {
            'genre': forms.Select(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'name': forms.TextInput(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'description': forms.Textarea(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'image': forms.FileInput(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'on_sale': forms.CheckboxInput(),
            'developers': forms.Select(attrs={
                'class': 'mx-3 gap-4 w-1/2 h-1/2 py-4 px-6 rounded-xl'
            }),
            'release_date': forms.widgets.DateInput(attrs={'type': 'date', 
                'class': 'mx-3 gap-4 w-1/6 h-1/2 py-4 px-6 rounded-xl'
            })
        }

content/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from wishlist.models import WishList

from .forms import GameEditForm, GameIntakeForm
from .models import Games, Genre


def game_catalog(request):
    query = request.GET.get('query', '')
    genre_id = request.GET.get('genre', 0)
    genres = Genre.objects.all()
    games = Games.objects.filter(on_sale=True)

    if genre_id:
        games = games.filter(genre_id=genre_id)

    if query:
        games = games.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'games/game_catalog_page.html', {
        'games': games,
        'query': query,
        'genres': genres,
        'genre_id': int(genre_id)
    })

def game_page(request, game_key):
    game = get_object_or_404(Games, pk=game_key)
    related_games = Games.objects.filter(genre=game.genre).exclude(pk=game_key)[0:3]
    
    user_wishlist = WishList.get_or_create(request.user)
    
    return render(request, 'games/game_page.html', {
        'game': game,
        'related_games': related_games,
        'on_wishlist': user_wishlist.on_wishlist(game)
    })

# TODO: Need to figure out what to do with these
@login_required
def game_intake(request):
    user_wishlist = WishList.get_or_create(request.user)
    if request.method == 'POST':
        form = GameIntakeForm(request.POST, request.FILES)
        
        if form.is_valid():
            new_game = form.save()
            
            return redirect(
                    'content:game_page', game_key=new_game.id,
                    on_wishlist=user_wishlist.on_wishlist(new_game)
                )
    else:
        
        form = GameIntakeForm()
    
    return render(request, 'games/game_intake.html', {
        'form': form,
        'title': 'New Game'
    })

# TODO: Need to figure out what to do with these
@login_required
def edit_game(request, game_key):
    game = get_object_or_404(Games, pk=game_key)
    user_wishlist = WishList.get_or_create(request.user)
    if request.method == 'POST':
        form = GameEditForm(request.POST, request.FILES, instance=game)

        if form.is_valid():
            form.save()

            return redirect(
                'content:game_page',
                game_key=form.id,
                on_wishlist=user_wishlist.on_wishlist(form)
            )
    else:
        form = GameEditForm(instance=game)

    return render(request, 'games/edit_game.html', {
        'form': form,
        'title': 'Edit game info',
        'on_wishlist': user_wishlist.on_wishlist(game)
    })

# TODO: Need to figure out what to do with these
@login_required
def remove_game(request, game_key):
    game = get_object_or_404(Games, pk=game_key)
    game.delete()

    return redirect('user_dash:dash_home')

content/templates/games/edit_game.html
{% extends 'general/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

content/templates/games/game_catalog_page.html
{% extends 'general/base.html' %}

{% block title %}Games{% endblock %}

{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1">
        <form method="get" action="{% url 'content:game_catalog' %}">
            <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}"
                placeholder="Find Games">

            <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
        </form>

        <hr class="my-6">

        <p class="font-semibold">Genres</p>

        <ul>
            {% for genre in genres %}
            <li class="py-2 px-2 rounded-xl{% if genre.id == genre_id %} bg-gray-200{% endif %}">
                <a href="{% url 'content:game_catalog' %}?query={{ query }}&genre={{ genre.id }}">{{ genre.name }}</a>
            </li>
            {% endfor %}
        </ul>

        <hr class="my-6">

        <p class="font-semibold">Clear filters</p>

        <ul>
            <li><a href="{% url 'content:game_catalog' %}"
                    class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
    </div>

    <div class="col-span-3">
        <div class="grid grid-cols-3 gap-3">
            {% for game in games %}
            <div>
                <a href="{% url 'content:game_page' game.id %}">
                    <div>
                        <img src="{{ game.image.url }}" class="rounded-t-xl" style="width: -moz-available;">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ game.name }}</h2>
                        <p class="text-gray-500">Price: {{ game.price }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

content/templates/games/game_intake.html
{% extends 'general/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3x1">{{title}}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <br>
    <br>
    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

content/templates/games/game_page.html
{% extends 'general/base.html' %}

{% block title %}{{ game.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ game.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ game.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ game.price }}</p>
        <p class="text-gray-500"><strong>Developers: </strong>{{ game.developers.name }}</p>
    
        {% if game.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ game.description }}
            </p>
        {% endif %}

        <a href="{% url 'messaging:create' game.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Join Coversation</a>

        {% if on_wishlist %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>Already on wishlist!</p>
                <a href="{% url 'wishlist:remove_from_wishlist' game.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Remove</a>
            </div>
        {% else %}  
            <a href="{% url 'wishlist:add_to_wishlist' game.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Add to Wishlist</a>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related games</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for game in related_games %}
            <div>
                <a href="{% url 'content:game_page' game.id %}">
                    <div>
                        <img src="{{ game.image.url }}" class="rounded-t-xl" style="width: -moz-available;">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ game.name }}</h2>
                        <p class="text-gray-500">Price: {{ game.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}