content/urls.py
from django.urls import path

from . import views

app_name = 'content'

urlpatterns = [
    path('', views.game_catalog, name='game_catalog'),
    # path('game_intake/', views.game_intake, name='game_intake'),
    path('<int:game_key>/', views.game_page, name='game_page'),
    # path('<int:game_key>/delete/', views.remove_game, name='remove_game'),
    # path('<int:game_key>/edit/', views.edit_game, name='edit_game'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'user_dash'

urlpatterns = [
    path('', views.dash_home, name='dash_home'),
]

frontend/urls.py
from django.urls import path
from django.contrib.auth import views as authentication
from .forms import UserLoginForm

from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.user_signup, name='user_signup'),
    path('login/', authentication.LoginView.as_view(
            template_name='general/login.html',
            authentication_form=UserLoginForm
        ), name='login')
]

messaging/urls.py
from django.urls import path

from . import views

app_name = 'messaging'

urlpatterns = [
    path('', views.message_home, name='message_home'),
    path('<int:message_key>/', views.message, name='message'),
    path('create/<int:game_key>/', views.new_message_group, name='create'),
]

steamapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('frontend.urls')),
    path('games/', include('content.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('messaging/', include('messaging.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class UserSignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2') 

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

frontend/views.py
from django.shortcuts import render, redirect

from content.models import Games, Genre

from .forms import UserSignUpForm

#homepage
def home(request):
    games = Games.objects.filter(on_sale=True)[0:6]
    genres = Genre.objects.all()
    
    return render(request, 'general/home.html', {
        'genres': genres,
        'games': games
    })

#contact page
def contact(request):
    return render(request, 'general/contact.html')

#user signup
def user_signup(request):
    if request.method == 'POST':
        form = UserSignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = UserSignUpForm()

    return render(request, 'general/user_signup.html', {
        'form': form
    })

frontend/templates/general/base.html
<!doctype html>

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Steam Sales</a>

        <div class="space-x-6">
            
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Featured</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Indies</a>
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Strategy</a>
            <a href="{% url 'content:game_catalog' %}" class="text-lg font-semibold hover:text-gray-500">Browse All</a>

            {% if request.user.is_authenticated %}
            <a href="{% url 'messaging:message_home' %}"
                class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Messaging</a>
            <a href="{% url 'user_dash:dash_home' %}"
                class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            {% else %}
            <a href="{% url 'frontend:user_signup' %}"
                class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{% url 'frontend:login' %}"
                class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-lg text-gray-500">This app hits Steam's API to retrieve the top games that are on sale right now
            </p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'frontend:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a>
                </li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>

</html>

frontend/templates/general/contact.html
{% extends 'general/base.html'%}

{% block title %}Contact{% endblock %}
Nothing here to contact since this is a Personal Project

{% block content %}
    <h1>The Contact page</h1>
{% endblock %}

frontend/templates/general/home.html
{% extends 'general/base.html'%}

{% block title %}Steam Sales{% endblock %}


{% block content %}    
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">On Sale!</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for game in games %}
                <div>
                    <a href="{% url 'content:game_page' game.id %}">
                        <div>
                            <img src="{{ game.image.url }}" class="rounded-t-xl" style="width: -moz-available;">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ game.name }}</h2>
                            <p class="text-gray-500">Price: {{ game.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Genres</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for genre in genres %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ genre.name }}</h2>
                            <p class="text-gray-500">{{ genre.items.count }} games</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

frontend/templates/general/login.html
{% extends 'general/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

frontend/templates/general/user_signup.html
{% extends 'general/base.html' %}

{% block title %}Sign up{% endblock %}
{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}